### ISSUE TITLE
When will v2022.04.03 be available for BSC support?

### ISSUE THREAD

**Issue by Fexiven** [wmitsuda/otterscan#268]
Sadly in the current otterscan version of erigon (v2022.04.02) the BSC chain is not supported, in erigon v2022.04.03 it is.

Would be amazing

**Comment by wmitsuda** [comment]
almost finishing porting otterscan API to the erigon 2 alpha series, hold on!

**Comment by wmitsuda** [comment]
Finished porting Otterscan API to Erigon 2: https://github.com/wmitsuda/erigon/releases/tag/v2022.06.01-otterscan
