### ISSUE TITLE
ots module not available in rpcdaemon

### ISSUE THREAD

**Issue by experimentalperson** [wmitsuda/otterscan#277]
Hello,

I have a running instance of erigon, and now I am trying to start otterscan.

I compiled the rpcdaemon from the provided repo ( https://github.com/wmitsuda/erigon )

but when running I get the following output:

`EROR[06-09|09:19:37.299] Unavailable modules in HTTP API list     unavailable=[ots] available="[eth erigon web3 net txpool]"                                                INFO[06-09|09:19:37.300] HTTP endpoint opened                     url=localhost:8545 ws=false ws.compression=false grpc=true grpc.port=8547                             
`

I compiled rpcdaemon from the referenced repo at this commit:

`git checkout 0929df8915936909278f4ce38a2e753630bb9dce`

what I'm doing wrong?

**Comment by wmitsuda** [comment]
did you enable the "ots" namespace when starting rpcdaemon?

see: https://github.com/wmitsuda/otterscan/blob/develop/docs/install.md#enable-otterscan-namespace-on-rpcdaemon

**Comment by experimentalperson** [comment]
@wmitsuda Yesss I enabled like this: 

`./rpcdaemon-otter --grpc  --http.api=eth,ots,erigon,web3,net,txpool --datadir=bsc-mainnet `

But when I start I get the above error

**Comment by wmitsuda** [comment]
try to checkout the tag directly, like: `git checkout v2022.06.02-otterscan`

**Comment by wmitsuda** [comment]
I guess you accidentally checked out a commit who is from upstream branch, so no "ots" support.

**Comment by experimentalperson** [comment]
Since I'm running an old version of erigon, I had to use that commit to build rpcdaemon, bevause of client/server version mismatch.

Is there a way I can solve this issue?

**Comment by wmitsuda** [comment]
Which erigon version are you running?

**Comment by experimentalperson** [comment]
`INFO[06-13|19:51:15.961] Build info                               git_branch=HEAD git_tag=v2022.06.02-otterscan git_commit=f03d08c5ce688352d3598f36d502a6a5cde7d3dc`

**Comment by wmitsuda** [comment]
that's strange, it doesn't match the commit hash for v2022.06.02-otterscan I have here, see:

<img width="1287" alt="image" src="https://user-images.githubusercontent.com/28685/173431583-6825684a-6abf-42f7-a32d-835d4549ad94.png">

**Comment by experimentalperson** [comment]
Yess Im sorry here is my `git log`

![image](https://user-images.githubusercontent.com/16927059/173531223-b8ca7380-8af4-48ad-b596-8f6bb4011c1f.png)

**Comment by experimentalperson** [comment]
Also its not clear if Its enough for me to use only `rpcdaemon` from your repository or also `erigon` compiled from your repo.

**Comment by wmitsuda** [comment]
you can replace just `rpcdaemon` as long it is compatible with the original `erigon` version, as currently we don't have modifications at sync level (this will change in future).

I tried to checkout the commit you mentioned, I can't identify if it is contained in the devel or beta stream, I'm almost sure it is in devel, which is currently the alpha series. So, at that time we didn't have a compatible Otterscan version, can't guarantee if it'll even work, I suggest you first upgrade your erigon installation itself to recent alpha.

**Comment by wmitsuda** [comment]
If you really want to feel adventurous, you can check and try it by yourself:

- git checkout v2022.04.02-otterscan -> latest beta compatible tag
- git checkout v2022.06.02-otterscan -> latest alpha compatible tag

compiling `rpcdaemon` from now on of these should work as long your erigon install is from one of these series, but can't guarantee everything will work.

**Comment by experimentalperson** [comment]
@wmitsuda  thank you man, I'm going to try that and let you know asap

> If you really want to feel adventurous, you can check and try it by yourself:
> 
> * git checkout v2022.04.02-otterscan -> latest beta compatible tag
> * git checkout v2022.06.02-otterscan -> latest alpha compatible tag
> 
> compiling `rpcdaemon` from now on of these should work as long your erigon install is from one of these series, but can't guarantee everything will work.

**Comment by experimentalperson** [comment]
@wmitsuda Hey man!!!! thank you very much, I compiled both erigon and rpcdaemon from `git checkout v2022.06.02-otterscan` and now they both seem to be working, will wait for the node to sync up and keep you updated!

**Comment by experimentalperson** [comment]
Node is still syncing, but I get the following:

![image](https://user-images.githubusercontent.com/16927059/174024209-5c3d9974-5ecd-4ab3-94e1-c838fb57e2d2.png)


Is it expected?

**Comment by experimentalperson** [comment]
I managed to open the rpc daemon on dockers private ip "172.17.0.1" and now I get this which seems okay, since node is still syncing

![image](https://user-images.githubusercontent.com/16927059/174027905-4526e4d5-9bc2-4e0e-8c4f-269366f9d1f7.png)

**Comment by experimentalperson** [comment]
Made it work!!! I had some problems with CORS that were not solved with --http.corsdomain "*", so I had to run otterscan docker locally

**Comment by wmitsuda** [comment]
glad you made it!

for running rpcdaemon not on localhost, be sure to follow the instructions on: https://github.com/wmitsuda/otterscan/blob/develop/docs/install.md#run-otterscan-docker-image-from-docker-hub, more specifically the ERIGON_URL variable.
