### ISSUE TITLE
ots_getContractCreator causing "method handler crashed"

### ISSUE THREAD

**Issue by Skemba** [wmitsuda/otterscan#281]
When calling the JSON RPC method ots_getContractCreator, for example with following data:
`{"jsonrpc":"2.0", "id": 67, "method":"ots_getContractCreator","params":["0xE592427A0AEce92De3Edee1F18E0157C05861564"]}`
it causes panic and returns:
`"error":{"code":-32000,"message":"method handler crashed"}}`

**Comment by wmitsuda** [comment]
Fixed, will generate another release of otterscan/erigon image, building...

**Comment by wmitsuda** [comment]
Release tag v2022.06.06-2-otterscan is now published and also on Docker Hub: https://github.com/wmitsuda/erigon/releases/tag/v2022.06.06-2-otterscan
