### ISSUE TITLE
Open verified contract in remix

### ISSUE THREAD

**Issue by ligi** [wmitsuda/otterscan#54]
In remix you can open a sourcify verified contract like tihs:

`https://remix.ethereum.org/#call=source-verification//fetchAndSave//0x0005e4b5454E00aE5FC4Eb6D37E0eb800C7bA1A9//3`

where 3 is the chainID and 0x0005e4b5454E00aE5FC4Eb6D37E0eb800C7bA1A9 is the contract address.

it would be awesome to have a "open in Remix" button next to the contract

**Comment by wmitsuda** [comment]
Initial implementation on branch feature/sourcify-tests, still need more UI work.

Will keep this open until integrated on develop branch.

**Comment by wmitsuda** [comment]
Released on v2021.09.02.
