### ISSUE TITLE
Navigating to ENS address page results in 404

### ISSUE THREAD

**Issue by sealer3** [wmitsuda/otterscan#557]
You can navigate to an address page like
```
/address/0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045
```
just fine.

But most links take you to the ENS name, like
```
/address/vitalik.eth
```

If you bookmark the page and try navigating to `/address/vitalik.eth` you will get a 404 error and nothing displayed on the page. But if you go to `/address/0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045` it will work.

**Comment by wmitsuda** [comment]
Use the production build :)

I've already notice that before, have no idea why it happens only in the dev environment, production build routes it fine.

Since it only happens in dev, I didn't investigate it further, will let it open, help welcome :)

**Comment by sealer3** [comment]
I've found the reason for this, but no fix yet. Vite thinks that the URL ending with a file extension is a file, and it looks for it but can't find the file `vitalik.eth` anywhere. If you try again without the `.eth` extension, the page loads (no longer a valid ENS name however).

**Comment by sealer3** [comment]
This turns out is a known vite problem. See this issue: https://github.com/vitejs/vite/issues/2190

The solution as in https://github.com/vitejs/vite/issues/2190#issuecomment-785541438 is to use the `vite-plugin-rewrite-all` npm package which was made specifically to "fix dev server not rewriting the path includes a dot". Or use a custom fallback like this: https://github.com/bluwy/publint/blob/f84b81e2c9f0191e4aab99fe20b7e1ba385f1ec7/site/vite.config.js#L32-L51

**Comment by wmitsuda** [comment]
thanks for researching a solution! just added the plugin and pushed into develop.
