### ISSUE TITLE
What's ots?

### ISSUE THREAD

**Issue by TangMonk** [wmitsuda/otterscan#709]
this is an awesome project!

But I have question about ots is it only avaliable on erigon? I cannot search any related topics about ots for erigon.

Is it only avaliabe for erigon?

**Comment by sealer3** [comment]
`ots` is a namespace of RPC calls created specifically for efficient queries for Otterscan. You can read about each RPC call in the documentation at [docs/custom-jsonrpc.md](https://github.com/wmitsuda/otterscan/blob/develop/docs/custom-jsonrpc.md), although some of the writing at the top is old and refers to running a patched Erigon instance, which is not necessary anymore.

The `ots` namespace has been merged with upstream Erigon, so all you need to run Otterscan is an Erigon archive node (see [docs/install.md](https://github.com/wmitsuda/otterscan/blob/develop/docs/install.md)). Other Ethereum clients don't support the `ots` namespace yet, only Erigon at the moment.

You can find the implementation of the `ots` namespace in the [Erigon codebase](https://github.com/ledgerwatch/erigon/tree/devel/cmd/rpcdaemon/commands).

**Comment by TangMonk** [comment]
@sealer3 

Oh, I got.

Is Otterscan same dev team with Erigon?

**Comment by wmitsuda** [comment]
Hi, I’m not from Erigon team, but we are very next to them, that allowed us to get our modifications merged into the client.

The ots API was also implemented into Akula, but that client was discontinued.

I hope that if this project becomes a successful product, that turns into an incentive for other newer clients to adopt and implement ots API as a competitive advantage.

**Comment by TangMonk** [comment]
> Hi, I’m not from Erigon team, but we are very next to them, that allowed us to get our modifications merged into the client.
> 
> The ots API was also implemented into Akula, but that client was discontinued.
> 
> I hope that if this project becomes a successful product, that turns into an incentive for other newer clients to adopt and implement ots API as a competitive advantage.

thanks, It is really awsome project
