### ISSUE TITLE
Specify erigon RPC daemon url

### ISSUE THREAD

**Issue by LefterisJP** [wmitsuda/otterscan#8]
How can I point the RPC daemon address where the patched erigon RPC lives if it's not same host?

**Comment by wmitsuda** [comment]
I responded in discord, but will answer here too if someone stumbles upon this issue:

You can change it by editing the src/ethersconfig.ts file. For now it is hardcoded, will make it a parameter in future.

**Comment by wmitsuda** [comment]
I'll let this issue open to remember as a TODO

**Comment by wmitsuda** [comment]
Fixed in develop branch, added an environment variable called REACT_APP_ERIGON_URL which should be exported at build time. I also added instructions in the README.md file.

Please check if that is ok for you, feel free to reopen if you have a better suggestion.
