### ISSUE TITLE
Add rpcdaemon connection indicator

### ISSUE THREAD

**Issue by LefterisJP** [wmitsuda/otterscan#9]
At the moment there seems to be no way to determine if we are connected to erigon's rpcdaemon apart from not seeing data loading when we request it.

It would be a good idea to have a connection indicator along with a troubleshooting message that you should make sure the daemon runs in the given url.

**Comment by wmitsuda** [comment]
It makes sense. As a workaround, you can check if in the homepage it is able to show the latest block known by your Erigon node.

**Comment by wmitsuda** [comment]
If you want to try unstable code, commit "931629d16ec972eee6fb587056417324fc254b08" on develop branch has a working code that does a series of probes the first time the page is loaded:

- It checks connectivity
- It checks if this an ETH node (probe eth_blockNumber)
- It checks if it is an Erigon node (probe erigon_getHeaderByNumber)
- It checks if it has Otterscan patches applied (probe ots_ custom method)

For each check, if it fails, we direct the user to the instructions.

**Comment by wmitsuda** [comment]
I will close this issue since in v2021.07.03 I introduced a check on page load which I hope will help diagnosing 99% of similar cases.

Feel free to open another issue for minor adjustments.
